server:
  port: 7040

spring:
  application:
    name: ${learner.name}
  datasource:
    driver-class-name: ${learner.database.driverClassName}
    url: ${learner.database.url}
    username: ${learner.database.username}
    password: ${learner.database.password}
  jpa:
    hibernate:
      ddl-auto: ${learner.database.ddl-auto}
    show-sql: ${learner.database.show-sql}
  profiles:
    active:
      - development
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka