learner:
  name: learner-service-api
  database:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/bg-learner
    username: postgres
    password: root
    ddl-auto: update
    show-sql: true