server:
  port: 7007
spring:
  application:
    name: Mail-Service
  mail:
    username: ${mail.username}
    password: ${mail.password}
    host: smtp.gmail.com
    port: 587
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  profiles:
    active: development
  kafka:
    bootstrap-servers: ${bootstrap-servers}
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.type.mapping: event:com.bloggios.notification.mailService.Payload.PostRegistrationOtpPayload
      group-id: otpId

application:
  version: @version@
  title: Email Service
