bloggios:
  port: 7000
  userService:
    name: UserService-development
  datasource:
    url: jdbc:mysql://localhost:3306/bloggios_learn
    username: ${DatabaseUser}
    password: ${DatabasePassword}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

logging:
  level:
    com.bloggios.userService.Service: debug